src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Original_Number_Rank__c</fullName>
        <label>Original Number Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PatientTest.cls
/*
 * test class for patient use case
*/

@isTest
private class PatientTest {
  static testMethod void testPatient() {
    Patient__c patient;
    
    patient = populatePatient();
    insert patient;
    
    patient = [select Id, Original_Number_Rank__c
               from Patient__c
               where Id = :patient.Id];
               
    System.assert(patient.Original_Number_Rank__c != null);
  }
  
  static Patient__c populatePatient() {
    return new Patient__c(Name = 'Test Patient',
                          Email__c = 'patient@htt.com',
                          Phone__c = '1231231234');
  }
}