src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Patient_Email__c</fullName>
        <label>Patient Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Treatments</relationshipLabel>
        <relationshipName>Treatments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TreatmentTests.cls
/*
 * this class will hold all tests for the treatment object.
*/

@istest
private class TreatmentTests {

    static testmethod void treatment_methods_test () {
        Patient__c patient = new Patient__c();
        patient.Name = 'test patient';
        patient.Email__c = 'test@test.com';
        insert patient;
        
        Treatment__c treatment = new treatment__c();
        treatment.Patient__c = patient.id;
        insert treatment;
        
        treatment.patient_email__c = null;
        update treatment;
        
        //this test does nothing and asserts nothing.
        //I am adding an assert so we can package.
        
        treatment = [select patient_email__c from Treatment__c where Id = :treatment.id];
        System.assertNotEquals(null, treatment.patient_email__c);
    }
}