src/objects/Patient__c.object
<CustomObject>
    <description>Core object in the PRM data model.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Original_Number_Rank__c</fullName>
        <label>Original Number Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Patient_Quality__c</fullName>
        <label>Patient Quality</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PatientRank.cls
/*
 * class to support the Patient ranker on insert a small app that ranks the quality of
 * a patient.
*/

public class PatientRank {

  private static Map<String, String> rankMap;
  private static String HIGH = 'High';
      
  //call only from Patient trigger
  public static void startRanking(List<Patient__c> pPatients) {
   
    PatientRank.populateRankMap();
    
    for(Patient__c patient : pPatients) {
      PatientRank.rankPatient(patient);
    }
  }
  
  private static void populateRankMap() {
    PatientRank.rankMap = new Map<String, String>();
    String[] keyValue;
    
    for (String s : Label.Patient_Ranking_Values.split(',')) {
      keyValue = s.split('=');
      PatientRank.rankMap.put(keyValue[0], keyValue[1]);
    }
  }
  
  private static void rankPatient(Patient__c pPatient) {
    Integer ranking = 0;
    
    ranking += (pPatient.Name != null) ? 1 : 0;
    ranking += (pPatient.Email__c != null) ? 1 : 0;
    ranking += (pPatient.Phone__c != null) ? 1 : 0;
    ranking += (pPatient.Mobile__c != null) ? 1 : 0;
    ranking += PatientRank.qualifyEmail(pPatient.Email__c);
    
    pPatient.Original_Number_Rank__c = Decimal.valueOf(ranking);
    
    if (PatientRank.rankMap.containsKey(String.valueOf(ranking))) {
      pPatient.Patient_Quality__c =
        PatientRank.rankMap.get(String.valueOf(ranking));
    } else {
      pPatient.Patient_Quality__c = PatientRank.HIGH;
    }
  }
  
  private static Integer qualifyEmail(String pEmail) {
    Integer returnValue = 0;
    
    if (pEmail != null) {
      returnValue += (!pEmail.contains('test')) ? 1 : 0;
    }
    return returnValue;
  }
}