src/objects/Procedure_Catalog__c.object
<CustomObject>
    <description>The list of all the procedures in the system.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <description>What Hospital, facility provides this Procedure.</description>
        <label>Facility</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Procedures</relationshipLabel>
        <relationshipName>Procedure_Catalogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Procedure_Code__c</fullName>
        <description>code to identify the procedure</description>
        <label>Procedure Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Procedure_Description__c</fullName>
        <description>Information about the procedure</description>
        <label>Procedure Description</label>
        <type>TextArea</type>
    </fields>
    <label>Procedure Catalog</label>
    <nameField>
        <label>Procedure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedure Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Procedure_Catalog_Price__c.object
<CustomObject>
    <description>The price that goes with this procedure</description>
    <fields>
        <fullName>List_Price__c</fullName>
        <description>The list for this currency of the Procedure</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Procedure_Catalog__c</fullName>
        <label>Procedure Catalog</label>
        <referenceTo>Procedure_Catalog__c</referenceTo>
        <relationshipLabel>Procedure Catalog Price</relationshipLabel>
        <relationshipName>Procedure_Catalogs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sale_Price__c</fullName>
        <label>Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Procedure Catalog Price</label>
    <nameField>
        <displayFormat>PCP{000000000}</displayFormat>
        <label>Procedure Catalog Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procedure Catalog Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Procedure_Line_Item__c.object
<CustomObject>
    <description>Conjunction object to link Procedures to Interactions.</description>
    <fields>
        <fullName>List_Price__c</fullName>
        <description>The List Cost of the Procedure</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Procedure__c</fullName>
        <description>What procedure are you adding to the Interaction</description>
        <label>Procedure</label>
        <referenceTo>Procedure_Catalog__c</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Procedures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale_Price__c</fullName>
        <description>if there is a sales on the procedure.</description>
        <label>Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Treatment__c</fullName>
        <label>Treatment</label>
        <referenceTo>Treatment__c</referenceTo>
        <relationshipLabel>Procedure Line Items</relationshipLabel>
        <relationshipName>Procedure_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Procedure Line Item</label>
    <nameField>
        <displayFormat>PLI{000000000}</displayFormat>
        <label>Procedure Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procedure Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Treatment__c.object
<CustomObject>
    <description>What Treatment is the patient interested in.</description>
    <fields>
        <fullName>Procedure__c</fullName>
        <label>Procedure</label>
        <picklist>
            <controllingField>Procedure_Category__c</controllingField>
            <picklistValues>
                <fullName>ACL Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angiogram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angioplasty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anti-Aging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ataxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatric - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breast Augmentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breast LIft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiac - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiomyopathy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cataract surgery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCSVI Diagnostics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCSVI for MS (venoplasty)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerebral Palsy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemotherapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Birth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cirrhosis &amp; Hepatitis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic Combo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cosmetic - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Limb Ischemia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT Scan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Consult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Crowns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Dentures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dental Implants</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Treatment</label>
    <nameField>
        <displayFormat>TR{00000000}</displayFormat>
        <label>Treatment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcedureLineExtension.cls
/*
 * class to control the procedure line process
 *
*/

public class ProcedureLineExtension {

  public Procedure_Line_Item__c line { get; set; }
  public Treatment__c treatment { get; private set; }
  public Boolean showLine { get; private set; }
  public Procedure_Catalog__c procedure { get; set; }
  
  public String testURL {get;set;} //delete for prod.
  
  public ProcedureLineExtension(ApexPages.StandardSetController sc) {
    
    this.line = (Procedure_Line_Item__c) sc.getRecord();
    /*this.treatment = [select Id
                      from Treatment__c
                      where Id =
                        :ApexPages.currentPage().getParameters().get('id')];*/
                        
                        
  }
  
  public void populateLine() {
    try {  

      this.procedure = [select Id,
                               Name,
                               Procedure_Code__c,
                               Procedure_Description__c,
                               Facility__r.Name,
                               (select Id,
                                       List_Price__c,
                                       Sale_Price__c
                               from Procedure_Catalogs__r)
                        from Procedure_Catalog__c
                        where Id = :this.line.Procedure__c
                        and Active__c = true];
      
      this.line.List_Price__c = this.procedure.Procedure_Catalogs__r[0].List_Price__c;
      this.line.Sale_Price__c = this.procedure.Procedure_Catalogs__r[0].Sale_Price__c;
                   
      this.showLine = true;
            
    } catch(QueryException e) {
      ApexPages.addMessages(e);
    }
  }
  
  public PageReference saveLine() {
    PageReference p;
    try {
      upsert this.line;
      
      p = new PageReference('/' + this.treatment.Id);
      
    } catch(Exception e) {
      ApexPages.addMessages(e);
    }
    return p;
  }
  
  static testMethod void testProcedureLineController() {
    Procedure_Line_Item__c line;
    List<Procedure_Line_Item__c> lines =
      new List<Procedure_Line_Item__c>();
    ProcedureLineExtension ple;
    
    line = new Procedure_Line_Item__c();
    lines.add(line);
    
    ple = new ProcedureLineExtension(
      new ApexPages.StandardSetController(lines)
    );
    
    ple.populateLine();
    ple.saveLine();
    
    System.assertEquals(ple.procedure, null);
    
  }
}